name: Ruby

on: push

jobs:
  run_spec:
    name: Run spec
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Test with Rspec
        run: |
          gem install bundler
          bundle install --path vendor/bundle --jobs 4 --retry 3
          bundle exec rspec
